### PR TITLE
Expand sinon peerDep to 17

### PR DESCRIPTION
**Pull request by Techn1x**
sinon 17 was released a few days ago
https://github.com/sinonjs/sinon/blob/main/CHANGES.md#1700

Looks like a small release, don't think it'll affect much in this repo & we should allow for it

I've run the test-app locally, all tests pass ✅

### CODE REVIEW

**Comment by SergeAstapov** [comment]
Thank you @Techn1x!

**Comment by Techn1x** [comment]
any chance for a patch release before the v2 addon format is merged? just in case there's issues with that

**Comment by SergeAstapov** [comment]
IMO it’s straightforward and no issues from my side.
@elwayman02 do you think you can handle that? We should be able to do v2 release somewhere this or max next week anyways I think

**Comment by elwayman02** [comment]
Ya, I'll see if I can get to it on Monday-ish.

**Comment by elwayman02** [comment]
Sorry for the delay on this, for some reason I can't download Node 18 locally on my machine, and that's preventing me from running the release-it script. :( Will get this released as soon as I can figure out why that's happening.

**Comment by elwayman02** [comment]
Weirdly, Node 16 works but Node 18 does 🙃

**Comment by elwayman02** [comment]
Ok, I *think* I got a release out?

**Comment by Techn1x** [comment]
yep! thanks a bunch!

**Pull request merged**
